### PR TITLE
Remove mention of old license

### PR DESCRIPTION
**Pull request by tupui**
We should not mention the previous license. This could be an issue with automatic tools parsing SciPy's source code.

xref https://github.com/scipy/scipy/pull/16155

### CODE REVIEW

**Comment by mdhaber** [comment]
Should UNU.RAN be added to https://github.com/scipy/scipy/blob/main/LICENSES_bundled.txt?

**Review by mdhaber — APPROVED** [review]
Changes look good. Should UNU.RAN be added to https://github.com/scipy/scipy/blob/main/LICENSES_bundled.txt, too?

**Comment by tupui** [comment]
Oh yes, sounds like a good idea.

**Comment by tupui** [comment]
Once this is in, I will make a PR to update the submodule and add the mention in this file.

**Comment by tirthasheshpatel** [comment]
Thanks @mdhaber and @tupui!

BTW, all the source files under the UNU.RAN source tree also mention GPL which needs to be removed too. I will remove them in a follow-up.

**Comment by tupui** [comment]
Oh really? Sorry I missed it in my search 👀

**Pull request merged**
